name: JS Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: ha-ha
        uses: ./.github/actions/joke-action

      - name: Setup node
        uses: actions/setup-node@v2
      - run: |
          npm i -g zx
          npm i @slack/web-api
      - name: test mjs script
        run: zx ./.github/workflows/scripts/test.mjs
        env:
#          GITHUB_REPOSITORY: ${{ github.event.repository }}
#          GITHUB_ACTOR: ${{ github.actor }}
          PR_LINK: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
