name: JS Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: ha-ha
        uses: ./.github/actions/joke-action

      - name: test mjs script
        run: |
          npm i -g zx
          zx ./.github/workflows/scripts/test.mjs
        env:
#          GITHUB_REPOSITORY: ${{ github.event.repository }}
#          GITHUB_ACTOR: ${{ github.actor }}
          PR_LINK: ${{ github.event.pull_request.html.href }}
          PR_TITLE: ${{ github.event.pull_request.title }}
